<?php

namespace App\Http\Requests\Pos;

use Illuminate\Foundation\Http\FormRequest;

class StartCardPaymentRequest extends FormRequest
{
    public function authorize(): bool
    {
        // Route is gated by the pos middleware.
        return true;
    }

    public function rules(): array
    {
        return [
            // Per-attempt idempotency token generated by the browser. UNIQUE in
            // the DB, so a double-click maps to one transaction / one charge.
            'idempotency_key'      => ['required', 'string', 'min:8', 'max:64'],

            'items'                => ['required', 'array', 'min:1'],
            'items.*.service_id'   => ['required', 'integer', 'exists:services,id'],
            'items.*.quantity'     => ['required', 'integer', 'min:1', 'max:10000'],
            'items.*.custom_price' => ['nullable', 'numeric', 'min:0', 'max:1000000'],
        ];
    }

    public function messages(): array
    {
        return [
            'items.required' => 'The cart is empty.',
            'items.min'      => 'The cart is empty.',
        ];
    }
}
